export type Worksheet = {
  id: string;
  courseSlug: string;
  topic: 'math' | 'science' | 'language' | 'geography' | 'arts' | 'technology';
  title: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  minutes: number;
  objectives: string[];
  tasks: string[];
  reflection: string;
};

export const TOPICS = [
  { key: 'all',        label: 'All Worksheets', icon: '🧭' },
  { key: 'math',       label: 'Math',           icon: '📐' },
  { key: 'science',    label: 'Science',         icon: '🔬' },
  { key: 'language',   label: 'Language',        icon: '📚' },
  { key: 'geography',  label: 'Geography',       icon: '🌍' },
  { key: 'arts',       label: 'Arts',            icon: '🎨' },
  { key: 'technology', label: 'Technology',      icon: '💻' },
] as const;

export const WORKSHEETS: Worksheet[] = [
  // ── Original 9 ───────────────────────────────────────────────────────────
  { id: 'math-number-market', courseSlug: 'foundations-of-math', topic: 'math', title: 'Number Market: Addition & Subtraction', level: 'Beginner', minutes: 20, objectives: ['Add and subtract within 20', 'Explain your strategy using words or drawings'], tasks: ['A mango costs 7 coins and a banana costs 5 coins. How many coins altogether?', 'You have 18 beans. You plant 6. How many are left?', 'Write your own market word problem and solve it.'], reflection: 'Which strategy helped most: counting on, drawing, or using objects?' },
  { id: 'math-fraction-cooking', courseSlug: 'foundations-of-math', topic: 'math', title: 'Cooking Fractions', level: 'Intermediate', minutes: 25, objectives: ['Recognize halves, thirds, and quarters', 'Compare simple fractions'], tasks: ['Draw a flatbread split into 2 equal pieces. Shade 1/2.', 'Which is larger: 1/3 or 1/4? Explain with a drawing.', 'A recipe uses 3/4 cup of water. Mark it on a cup sketch.'], reflection: 'Where do you use fractions at home?' },
  { id: 'science-water-cycle', courseSlug: 'earth-and-water-science', topic: 'science', title: 'Water Cycle Field Notes', level: 'Beginner', minutes: 25, objectives: ['Name evaporation, condensation, and precipitation', 'Connect weather observations to the water cycle'], tasks: ['Sketch clouds and arrows showing water moving up and down.', 'Observe the sky for 5 minutes. What clues show rain may come?', 'Put these in order: cloud forms, rain falls, puddle dries.'], reflection: 'How does rain support your community?' },
  { id: 'science-plant-detective', courseSlug: 'living-world', topic: 'science', title: 'Plant Detective', level: 'Beginner', minutes: 20, objectives: ['Identify roots, stems, leaves, flowers', 'Describe what plants need to grow'], tasks: ['Find a safe plant to observe. Draw and label four parts.', 'List three things this plant needs.', 'Predict what happens if the plant gets no sunlight for a week.'], reflection: 'What plants are important where you live?' },
  { id: 'language-story-map', courseSlug: 'english-beginners', topic: 'language', title: 'Story Map Builder', level: 'Beginner', minutes: 30, objectives: ['Identify character, setting, problem, and solution', 'Write a short paragraph from a plan'], tasks: ['Choose a character from your community.', 'Describe where the story happens using three details.', 'Write the problem and solution in two complete sentences.'], reflection: 'What makes a story easy to remember?' },
  { id: 'language-vocab-trail', courseSlug: 'swahili-basics', topic: 'language', title: 'Vocabulary Trail', level: 'Beginner', minutes: 15, objectives: ['Practice five new words', 'Use each word in context'], tasks: ["Pick five useful words from today's lesson.", 'Draw a small icon for each word.', 'Write one sentence using each word.'], reflection: 'Which word will you use today?' },
  { id: 'geo-map-my-route', courseSlug: 'maps-and-places', topic: 'geography', title: 'Map My Route', level: 'Beginner', minutes: 25, objectives: ['Use symbols and directions', 'Create a simple route map'], tasks: ['Draw your route from home to a learning place.', 'Add a legend with at least four symbols.', 'Write directions using north, south, east, or west.'], reflection: 'What landmark helps you avoid getting lost?' },
  { id: 'arts-patterns', courseSlug: 'arts-and-culture', topic: 'arts', title: 'Patterns Around Us', level: 'Beginner', minutes: 20, objectives: ['Recognize repeating patterns', 'Create a pattern inspired by local art'], tasks: ['Find or imagine a pattern with two repeating shapes.', 'Create an ABAB or AABB pattern border.', 'Explain what colors or shapes you chose and why.'], reflection: 'How can art tell a community story?' },
  { id: 'tech-safe-password', courseSlug: 'technology-frontier', topic: 'technology', title: 'Strong Password Workshop', level: 'Beginner', minutes: 20, objectives: ['Explain why passwords matter', 'Create a memorable strong password pattern'], tasks: ['List three things a password should not include.', 'Build a practice password from a phrase, numbers, and symbols.', 'Write two safety rules for shared devices.'], reflection: 'How can you keep an account safe without writing the password publicly?' },

  // ── Math extras (8+) ─────────────────────────────────────────────────────
  { id: 'math-geometry-explorer', courseSlug: 'foundations-of-math', topic: 'math', title: 'Geometry Explorer', level: 'Beginner', minutes: 25, objectives: ['Identify 2D and 3D shapes by name', 'Count sides, vertices, and faces'], tasks: ['Draw a triangle, square, and hexagon. Label the sides and corners.', 'Find three 3D shapes in your home (box, ball, can). Name each.', 'Sort the shapes: which have all equal sides?'], reflection: 'Where do you see geometric shapes in buildings around you?' },
  { id: 'math-measurement', courseSlug: 'foundations-of-math', topic: 'math', title: 'Measurement Matters', level: 'Beginner', minutes: 30, objectives: ['Measure length, weight, and volume', 'Choose the right unit for each measurement'], tasks: ['Use a ruler to measure three objects in centimetres.', 'Estimate the weight of a book, a stone, and a cup of water. Order them lightest to heaviest.', 'Fill a cup with water. Estimate how many cups fill a large container.'], reflection: 'Which measurement skill do you use most often in daily life?' },
  { id: 'math-data-graphs', courseSlug: 'foundations-of-math', topic: 'math', title: 'Data Detective', level: 'Intermediate', minutes: 30, objectives: ['Collect and record tally data', 'Draw a bar graph from a tally chart'], tasks: ['Survey 10 classmates or neighbours: what is their favourite fruit? Record with tally marks.', 'Draw a bar graph from your tally results. Label axes and title.', 'Write two sentences about what the data shows.'], reflection: 'What surprised you about the results?' },
  { id: 'math-algebra-basics', courseSlug: 'algebra-basics', topic: 'math', title: 'Algebra Basics: Mystery Numbers', level: 'Intermediate', minutes: 25, objectives: ['Use a symbol to represent an unknown number', 'Solve one-step equations by inspection'], tasks: ['Find the mystery number: □ + 5 = 12. Show your thinking.', 'Solve: 3 × □ = 18. Explain how you found the answer.', 'Write your own mystery-number problem and swap with a friend.'], reflection: 'How is finding a mystery number like following a trail of clues?' },
  { id: 'math-time-money', courseSlug: 'foundations-of-math', topic: 'math', title: 'Time & Money Challenges', level: 'Beginner', minutes: 20, objectives: ['Read analogue and digital clocks', 'Add and give change using local currency'], tasks: ['Draw clock faces for 7:30, 11:15, and 4:45.', 'You have 50 shillings. A pen costs 12. How much change do you receive?', 'A lesson starts at 9:00 and ends at 9:45. How long is the lesson?'], reflection: 'Why is it useful to read a clock without using a phone?' },
  { id: 'math-patterns', courseSlug: 'foundations-of-math', topic: 'math', title: 'Pattern Power', level: 'Beginner', minutes: 20, objectives: ['Identify and extend number and shape patterns', 'Describe the rule of a pattern in words'], tasks: ['Continue the pattern: 2, 4, 6, 8, __.', 'Draw the next shape: ○ △ ○ △ ○ __.', 'Create your own pattern with at least 6 terms and write its rule.'], reflection: 'How do patterns help us predict what comes next?' },
  { id: 'math-multiplication', courseSlug: 'foundations-of-math', topic: 'math', title: 'Multiplication Trails', level: 'Intermediate', minutes: 25, objectives: ['Recall multiplication facts up to 5×10', 'Use arrays and skip counting as strategies'], tasks: ['Draw an array for 3×4 and write the matching multiplication sentence.', 'Skip count by 5s to find 5×7. Show each step.', 'A farmer plants 6 rows with 8 seeds each. How many seeds in total?'], reflection: 'Which times table do you find hardest? What trick could help you remember it?' },
  { id: 'math-division', courseSlug: 'foundations-of-math', topic: 'math', title: 'Division Discovery', level: 'Intermediate', minutes: 25, objectives: ['Divide by grouping and sharing equally', 'Connect division to multiplication facts'], tasks: ['Share 24 mangoes equally among 4 friends. How many each? Draw groups.', 'Use the fact 5×6=30 to solve 30÷6. Explain the connection.', 'A box holds 8 pencils. You have 40 pencils. How many boxes are needed?'], reflection: 'When do you divide things equally in real life?' },
  { id: 'math-place-value', courseSlug: 'foundations-of-math', topic: 'math', title: 'Place Value Safari', level: 'Beginner', minutes: 20, objectives: ['Identify hundreds, tens, and ones', 'Compare and order 3-digit numbers'], tasks: ['Write the number 347 in a place value chart (hundreds | tens | ones).', 'Order from smallest to largest: 518, 251, 815, 125.', 'What is the value of the digit 6 in the number 462?'], reflection: 'How does place value help you add large numbers more easily?' },

  // ── Science extras ────────────────────────────────────────────────────────
  { id: 'science-simple-machines', courseSlug: 'earth-and-water-science', topic: 'science', title: 'Simple Machines Around Us', level: 'Intermediate', minutes: 25, objectives: ['Name the 6 simple machines', 'Give real-life examples of each'], tasks: ['Find one example of a lever, a wheel, and an inclined plane near you.', 'Explain how a wedge makes cutting easier.', 'Design a simple tool using two or more simple machines. Sketch and label it.'], reflection: 'How have simple machines changed daily work in your community?' },
  { id: 'science-states-of-matter', courseSlug: 'living-world', topic: 'science', title: 'States of Matter', level: 'Beginner', minutes: 20, objectives: ['Describe solid, liquid, and gas', 'Give examples of matter changing state'], tasks: ['List two solids, two liquids, and two gases you encounter daily.', 'Describe what happens when ice is placed in the sun. Name the process.', 'Draw and label a diagram showing water as solid, liquid, and gas.'], reflection: 'Why does rain sometimes fall as ice? What conditions cause the change?' },
  { id: 'science-food-chains', courseSlug: 'living-world', topic: 'science', title: 'Food Chain Explorer', level: 'Beginner', minutes: 25, objectives: ['Define producer, consumer, and decomposer', 'Build a simple food chain from local plants and animals'], tasks: ['Name three plants (producers) from your region.', "Build a food chain: grass → ? → ? Label each organism's role.", 'What would happen if all the grass disappeared? Write two consequences.'], reflection: 'How does every living thing depend on others to survive?' },
  { id: 'science-weather', courseSlug: 'earth-and-water-science', topic: 'science', title: 'Weather Watchers', level: 'Beginner', minutes: 30, objectives: ['Record weather observations over three days', 'Identify patterns in temperature and rainfall'], tasks: ['Observe the weather for three days. Record: cloudy/clear, hot/warm/cool, rain/no rain.', 'What pattern did you notice across the three days?', "How does today's weather affect what people in your community do?"], reflection: 'Why is understanding weather important for farmers and travellers?' },

  // ── Language extras ───────────────────────────────────────────────────────
  { id: 'language-punctuation', courseSlug: 'english-beginners', topic: 'language', title: 'Punctuation Pathfinder', level: 'Beginner', minutes: 20, objectives: ['Use full stops, commas, and question marks correctly', 'Identify where punctuation belongs in a passage'], tasks: ['Add punctuation to: "the boy ran home it was dark outside did anyone see him"', 'Write three sentences: one statement, one question, one exclamation.', 'Explain in your own words: what does a comma tell the reader to do?'], reflection: 'How does punctuation change the meaning of a sentence?' },
  { id: 'language-letter-writing', courseSlug: 'english-beginners', topic: 'language', title: 'Letter Writing Trail', level: 'Intermediate', minutes: 30, objectives: ['Identify the structure of a formal and informal letter', 'Write a letter with correct greeting, body, and closing'], tasks: ['Label the parts of the sample letter: date, greeting, body, closing, signature.', 'Write a short informal letter to a friend describing your favourite day.', 'Now write one sentence from the same letter in formal style for a teacher.'], reflection: 'When would you choose a formal letter over an informal one?' },
  { id: 'language-comprehension', courseSlug: 'english-beginners', topic: 'language', title: 'Reading Comprehension Trail', level: 'Intermediate', minutes: 30, objectives: ['Read a passage and answer literal and inferential questions', 'Identify the main idea and supporting details'], tasks: ['Read the passage provided. What is the main idea? Write one sentence.', 'List three details that support the main idea.', 'Write one question the passage does NOT answer but makes you wonder about.'], reflection: 'What reading strategy helped you most: scanning, re-reading, or asking questions?' },
  { id: 'language-poetry', courseSlug: 'swahili-basics', topic: 'language', title: 'Poetry Corner', level: 'Intermediate', minutes: 25, objectives: ['Recognize rhyme, rhythm, and imagery in a poem', 'Write a short poem using sensory language'], tasks: ['Read the sample poem. Circle two words that create a strong image.', 'Write a four-line poem about something you see every morning.', 'Read your poem aloud. Mark which syllables feel stressed (louder).'], reflection: 'How is a poem different from a story? What can a poem do that a story cannot?' },

  // ── Geography extras ──────────────────────────────────────────────────────
  { id: 'geo-continents-oceans', courseSlug: 'maps-and-places', topic: 'geography', title: 'Continents and Oceans', level: 'Beginner', minutes: 20, objectives: ['Name the 7 continents and 5 oceans', 'Locate them on a blank world map'], tasks: ['Label the 7 continents on the outline map.', 'Shade the 5 oceans in blue and label each.', 'Which continent do you live on? Write two interesting facts about it.'], reflection: 'Why is Africa sometimes called the "cradle of humanity"?' },
  { id: 'geo-climate-zones', courseSlug: 'maps-and-places', topic: 'geography', title: 'Climate Zones Explorer', level: 'Intermediate', minutes: 25, objectives: ['Describe tropical, temperate, and polar climate zones', 'Connect climate zone to vegetation and lifestyle'], tasks: ['Match each climate zone to its typical vegetation: rainforest, grassland, tundra.', 'Describe how daily life (clothing, food, shelter) differs between tropical and polar zones.', 'What climate zone do you live in? Give two pieces of evidence.'], reflection: 'How does climate affect what crops farmers can grow?' },
  { id: 'geo-natural-resources', courseSlug: 'maps-and-places', topic: 'geography', title: 'Natural Resources Map', level: 'Intermediate', minutes: 25, objectives: ['Differentiate renewable and non-renewable resources', 'Identify key resources in your region'], tasks: ['List three renewable and three non-renewable resources.', 'Mark two important natural resources found in your country on a sketch map.', 'Explain one way your community uses or depends on a local resource.'], reflection: 'How can we use resources responsibly for future generations?' },
  { id: 'geo-population', courseSlug: 'maps-and-places', topic: 'geography', title: 'Population Patterns', level: 'Advanced', minutes: 30, objectives: ['Read a population density map', 'Explain why people cluster in certain areas'], tasks: ['Look at the population map. Which areas are most densely populated?', 'List three reasons why people choose to live near rivers or coasts.', 'Describe one challenge and one benefit of living in a densely populated city.'], reflection: 'How does population density affect access to schools, hospitals, and water?' },

  // ── Arts extras ───────────────────────────────────────────────────────────
  { id: 'arts-color-theory', courseSlug: 'arts-and-culture', topic: 'arts', title: 'Color Theory Studio', level: 'Beginner', minutes: 25, objectives: ['Identify primary and secondary colors', 'Create a simple color wheel using mixing'], tasks: ['Name the three primary colors and what they create when mixed.', 'Mix (or draw) red+yellow, yellow+blue, blue+red. Label each result.', 'Choose two complementary colors. Design a small pattern using them.'], reflection: 'How do artists use color to show emotion or mood?' },
  { id: 'arts-rhythm', courseSlug: 'arts-and-culture', topic: 'arts', title: 'Rhythm and Beat', level: 'Beginner', minutes: 20, objectives: ['Distinguish beat and rhythm', 'Clap and notate a simple rhythmic pattern'], tasks: ['Clap a steady beat for 8 counts. This is the beat. Now clap a pattern over it.', 'Notate your rhythm using long lines (—) for half-beats and dots (•) for quarter-beats.', 'Create a 4-beat rhythm using hand claps and foot stomps. Perform it twice.'], reflection: 'Where do you hear rhythm in everyday life — speech, work, music?' },
  { id: 'arts-storytelling', courseSlug: 'arts-and-culture', topic: 'arts', title: 'Storytelling Through Art', level: 'Intermediate', minutes: 30, objectives: ['Understand how visual art tells a story', 'Create a three-panel comic or storyboard'], tasks: ['Choose a local folktale or personal memory.', 'Draw three panels: beginning, middle, end. Add short captions.', 'Share your storyboard and ask: what did your viewer understand without reading the captions?'], reflection: 'What details in your art helped tell the story without words?' },
  { id: 'arts-architecture', courseSlug: 'arts-and-culture', topic: 'arts', title: 'Architecture Around Us', level: 'Intermediate', minutes: 25, objectives: ['Observe how buildings reflect culture and environment', 'Sketch a building and identify its design features'], tasks: ['Find a building near you. Sketch its front view. Label: walls, roof, windows, door.', 'What materials were used? Why are those materials good for your climate?', 'Design your ideal school building. Include at least three features that help students learn.'], reflection: 'How do buildings tell us about the people who built them and what they valued?' },

  // ── Technology extras ─────────────────────────────────────────────────────
  { id: 'tech-internet-safety', courseSlug: 'technology-frontier', topic: 'technology', title: 'Internet Safety Expedition', level: 'Beginner', minutes: 20, objectives: ['Identify risky online behaviours', 'Apply safe-sharing rules'], tasks: ['List five types of personal information you should never share online.', 'Read the scenario: "A stranger online asks for your school name." What do you do?', 'Write three rules for your household about safe internet use.'], reflection: 'Who can you talk to if something online makes you uncomfortable?' },
  { id: 'tech-binary', courseSlug: 'intro-to-computers', topic: 'technology', title: 'Binary Numbers Decoded', level: 'Intermediate', minutes: 25, objectives: ['Understand that computers use binary (0 and 1)', 'Convert small decimal numbers to binary'], tasks: ['Count in binary: 0, 1, 10, 11, __ (what comes next?)', 'Convert the decimal number 5 to binary. Show each step.', 'Decode this binary message: 01001000 01001001 (each byte is one letter — use a binary table).'], reflection: 'Why do computers use binary instead of the decimal numbers we use daily?' },
  { id: 'tech-how-computers-think', courseSlug: 'intro-to-computers', topic: 'technology', title: 'How Computers Think', level: 'Beginner', minutes: 20, objectives: ['Describe input, process, output', 'Give examples of each from everyday devices'], tasks: ['For a calculator: what is the input? The process? The output?', 'Identify input, process, and output for a mobile phone sending a text.', 'Design a simple "robot" that makes tea. List its input, process, and output.'], reflection: 'How is human thinking similar to and different from computer processing?' },
  { id: 'tech-digital-citizenship', courseSlug: 'digital-literacy', topic: 'technology', title: 'Digital Citizenship Charter', level: 'Intermediate', minutes: 25, objectives: ['Define digital citizenship and online rights/responsibilities', 'Write a personal digital pledge'], tasks: ['List two digital rights (e.g. privacy) and two digital responsibilities (e.g. respect).', 'Read the cyberbullying scenario. How should the witness respond? Give two actions.', 'Write a five-point Digital Citizenship Pledge you commit to following.'], reflection: 'How does your behaviour online affect others even when you cannot see them?' },
  { id: 'tech-spreadsheets', courseSlug: 'digital-literacy', topic: 'technology', title: 'Spreadsheet Skills', level: 'Advanced', minutes: 30, objectives: ['Understand rows, columns, and cells', 'Use SUM and AVERAGE formulas on a small dataset'], tasks: ['Draw a spreadsheet grid. Label row 1 as headers: Name, Score 1, Score 2, Total.', 'Fill in data for 4 students. Write the SUM formula that would calculate each total.', 'Calculate the class average score. Explain each step.'], reflection: 'How could a spreadsheet help a small business or farm track income and expenses?' },
];
